default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quizzy_development

test:
  <<: *default
  database: quizzy_test

production:
  <<: *default
  database: quizzy_production
  username: quizzy
  password: <%= ENV['URL-SHORTENER_DATABASE_PASSWORD'] %>
